FROM node:20-bookworm-slim

ENV NEXT_TELEMETRY_DISABLED=1
WORKDIR /app/frontend

COPY frontend/package*.json ./
COPY frontend/vendor ./vendor
RUN npm ci

COPY frontend .
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
