FROM node:20-bookworm-slim

ENV NEXT_TELEMETRY_DISABLED=1
WORKDIR /app

COPY package*.json ./
COPY sdk/package.json ./sdk/package.json
COPY web/package.json ./web/package.json
COPY contracts/package.json ./contracts/package.json
RUN npm ci

COPY sdk ./sdk
COPY web ./web
COPY contracts ./contracts

WORKDIR /app/web
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
